-- ═══════════════════════════════════════════════════════════════════════════
-- PATIENT HOSPITAL NUMBER FORMAT
--
-- The canonical hospital number is now:
--   NVH00001   (NVH + five zero-padded digits, no hyphen, no E)
--
-- Every patient uses one shared NVH series regardless of how they were
-- registered:
--   • front-desk EMR registration
--   • bulk CSV import
--
-- Legacy values are rewritten during migration:
--   NVHE-000001  → NVH00001
--   NVH-000001   → NVH00001
--
-- New values are generated by replacing the old two-sequence logic with a
-- single race-free sequence. Existing numbers are re-numbered deterministically
-- so removing the E / hyphen never creates duplicates.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Pool both old prefixes into one shared sequence ─────────────────────────
create sequence if not exists public.seq_hospital_number_nvh start with 1;

-- 2. Allocate the next number from the single shared series ───────────────────
create or replace function public.next_hospital_number(p_prefix text)
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_seq bigint;
begin
  v_seq := nextval('public.seq_hospital_number_nvh');
  return 'NVH' || lpad(v_seq::text, 5, '0');
end;
$$;

-- 3. Push the shared counter past an explicit number (from a bulk-upload CSV or
--    a legacy value). Idempotent: the counter only ever moves forward.
create or replace function public.advance_hospital_number_seq(p_prefix text, p_number text)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_n   bigint;
  v_max bigint;
begin
  if p_number is null or trim(p_number) = '' then
    return;
  end if;

  -- Accept legacy/hyphenated forms: NVHE-000001, NVH-000001, NVH00001, …
  v_n := (regexp_match(upper(p_number), '([0-9]+)$'))[1]::bigint;
  if v_n is null or v_n < 1 then
    return;
  end if;

  -- Highest suffix already in use anywhere in the shared NVH series.
  select coalesce(max((regexp_match(hospital_number, '([0-9]+)$'))[1]::bigint), 0)
    into v_max
    from public.patients
   where hospital_number is not null
     and hospital_number ~ '^NVH';

  execute format(
    'select setval(%L, greatest(%s, %s), true)',
    'public.seq_hospital_number_nvh',
    v_n,
    v_max
  );
end;
$$;

-- The old EMR-only sequence is no longer used by either function.
drop sequence if exists public.seq_hospital_number_nvhe;

-- Only authenticated staff may use the generators (the server client always
-- calls these as the signed-in staff member).
revoke execute on function public.next_hospital_number(text) from public;
revoke execute on function public.advance_hospital_number_seq(text, text) from public;
grant execute on function public.next_hospital_number(text) to authenticated;
grant execute on function public.advance_hospital_number_seq(text, text) to authenticated;

-- 4. Rewrite existing numbers to the canonical format ────────────────────────
--
-- We keep an existing numeric suffix when it is unique (so paper-record numbers
-- from bulk uploads are preserved where possible). Because the old NVHE and NVH
-- prefixes both started at 1, simply stripping the prefix can collide — those
-- colliding rows are assigned the next free numbers in the same series.
do $$
declare
  v_max bigint;
begin
  drop table if exists tmp_hospital_number_reassign;
  create temp table tmp_hospital_number_reassign as
    select id
      from public.patients
     where false;
  alter table tmp_hospital_number_reassign add column hospital_number text;
  alter table tmp_hospital_number_reassign add primary key (id);

  -- Assign the canonical number for every patient in created-at order.
  with base as (
    select id,
           coalesce((regexp_match(upper(hospital_number), '([0-9]+)$'))[1]::bigint, 0) as legacy_num,
           row_number() over (
             partition by coalesce((regexp_match(upper(hospital_number), '([0-9]+)$'))[1]::bigint, 0)
             order by created_at asc nulls last, id asc
           ) as rn,
           count(*) over (
             partition by coalesce((regexp_match(upper(hospital_number), '([0-9]+)$'))[1]::bigint, 0)
           ) as dup_count,
           row_number() over (order by created_at asc nulls last, id asc) as rec_rn
      from public.patients
  ),
  kept as (
    select id,
           legacy_num,
           rec_rn,
           case
             when legacy_num > 0 and (dup_count = 1 or rn = 1) then legacy_num
             else null
           end as kept_num
      from base
  ),
  max_kept as (
    select coalesce(max(kept_num), 0) as m from kept
  ),
  dups as (
    select id,
           row_number() over (order by rec_rn) as dup_rn
      from kept
     where kept_num is null
  )
  insert into tmp_hospital_number_reassign (id, hospital_number)
  select k.id,
         'NVH' || lpad(coalesce(k.kept_num, m.m + d.dup_rn)::text, 5, '0')
    from kept k
   cross join max_kept m
   left join dups d
     on d.id = k.id;

  -- First move every existing value to a unique temporary value so the unique
  -- index cannot reject the final re-numbering mid-update.
  update public.patients p
     set hospital_number = '__HN_RENUMBER__' || p.id::text
   where hospital_number is not null;

  update public.patients p
     set hospital_number = t.hospital_number
    from tmp_hospital_number_reassign t
   where p.id = t.id;

  -- Point the shared sequence just past the highest number now in use.
  select coalesce(max((regexp_match(hospital_number, '([0-9]+)$'))[1]::bigint), 0)
    into v_max
    from public.patients
   where hospital_number is not null
     and hospital_number ~ '^NVH';

  execute 'alter sequence public.seq_hospital_number_nvh restart with 1;';
  if v_max > 0 then
    execute format('select setval(%L, %s, true)', 'public.seq_hospital_number_nvh', v_max);
  end if;

  drop table if exists tmp_hospital_number_reassign;
end;
$$;
